<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        \DB::table('permissions')->truncate();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        \DB::table('permissions')->insert([
            [
                'id'            => 1,
                'name'          => 'entity-company-create',
                'display_name'  => 'Company Create',
                'description'   => 'Create new company',
                'type'          => 1,
                'submod_id'     => 1,
            ],
            [
                'id'            => 2,
                'name'          => 'entity-company-read',
                'display_name'  => 'Company Read',
                'description'   => 'Read company data',
                'type'          => 2,
                'submod_id'     => 1,
            ],
            [
                'id'            => 3,
                'name'          => 'entity-company-not-allowed',
                'display_name'  => 'Company Not Allowed',
                'description'   => 'Can not allow access company',
                'type'          => 3,
                'submod_id'     => 1,
            ],
            [
                'id'            => 4,
                'name'          => 'entity-bank-create',
                'display_name'  => 'Bank Create',
                'description'   => 'Create new Bank',
                'type'          => 1,
                'submod_id'     => 2,
            ],
            [
                'id'            => 5,
                'name'          => 'entity-bank-read',
                'display_name'  => 'Bank Read',
                'description'   => 'Read Bank data',
                'type'          => 2,
                'submod_id'     => 2,
            ],
            [
                'id'            => 6,
                'name'          => 'entity-bank-not-allowed',
                'display_name'  => 'Bank Not Allowed',
                'description'   => 'Can not allow access Bank',
                'type'          => 3,
                'submod_id'     => 2,
            ],
            [
                'id'            => 7,
                'name'          => 'entity-bpjsw-create',
                'display_name'  => 'BPJS Worker Create',
                'description'   => 'Create new BPJS Worker',
                'type'          => 1,
                'submod_id'     => 3,
            ],
            [
                'id'            => 8,
                'name'          => 'entity-bpjsw-read',
                'display_name'  => 'BPJS Worker Read',
                'description'   => 'Read BPJS Worker data',
                'type'          => 2,
                'submod_id'     => 3,
            ],
            [
                'id'            => 9,
                'name'          => 'entity-bpjsw-not-allowed',
                'display_name'  => 'BPJS Worker Not Allowed',
                'description'   => 'Can not allow access BPJS Worker',
                'type'          => 3,
                'submod_id'     => 3,
            ],
            [
                'id'            => 10,
                'name'          => 'entity-bpjsh-create',
                'display_name'  => 'BPJS Healthcare Create',
                'description'   => 'Create new BPJS Healthcare',
                'type'          => 1,
                'submod_id'     => 4,
            ],
            [
                'id'            => 11,
                'name'          => 'entity-bpjsh-read',
                'display_name'  => 'BPJS Healthcare Read',
                'description'   => 'Read BPJS Healthcare data',
                'type'          => 2,
                'submod_id'     => 4,
            ],
            [
                'id'            => 12,
                'name'          => 'entity-bpjsh-not-allowed',
                'display_name'  => 'BPJS Healthcare Not Allowed',
                'description'   => 'Can not allow access BPJS Healthcare',
                'type'          => 3,
                'submod_id'     => 4,
            ],
            [
                'id'            => 13,
                'name'          => 'entity-tax-create',
                'display_name'  => 'Tax Create',
                'description'   => 'Create new Tax',
                'type'          => 1,
                'submod_id'     => 5,
            ],
            [
                'id'            => 14,
                'name'          => 'entity-tax-read',
                'display_name'  => 'Tax Read',
                'description'   => 'Read Tax data',
                'type'          => 2,
                'submod_id'     => 5,
            ],
            [
                'id'            => 15,
                'name'          => 'entity-tax-not-allowed',
                'display_name'  => 'Tax Not Allowed',
                'description'   => 'Can not allow access Tax',
                'type'          => 3,
                'submod_id'     => 5,
            ],
            [
                'id'            => 16,
                'name'          => 'entity-dept1-create',
                'display_name'  => 'Department #1 Create',
                'description'   => 'Create new Department #1',
                'type'          => 1,
                'submod_id'     => 6,
            ],
            [
                'id'            => 17,
                'name'          => 'entity-dept1-read',
                'display_name'  => 'Department #1 Read',
                'description'   => 'Read Department #1 data',
                'type'          => 2,
                'submod_id'     => 6,
            ],
            [
                'id'            => 18,
                'name'          => 'entity-dept1-not-allowed',
                'display_name'  => 'Department #1 Not Allowed',
                'description'   => 'Can not allow access Department #1',
                'type'          => 3,
                'submod_id'     => 6,
            ],
            [
                'id'            => 19,
                'name'          => 'entity-dept2-create',
                'display_name'  => 'Department #2 Create',
                'description'   => 'Create new Department #2',
                'type'          => 1,
                'submod_id'     => 7,
            ],
            [
                'id'            => 20,
                'name'          => 'entity-dept2-read',
                'display_name'  => 'Department #2 Read',
                'description'   => 'Read Department #2 data',
                'type'          => 2,
                'submod_id'     => 7,
            ],
            [
                'id'            => 21,
                'name'          => 'entity-dept2-not-allowed',
                'display_name'  => 'Department #2 Not Allowed',
                'description'   => 'Can not allow access Department #2',
                'type'          => 3,
                'submod_id'     => 7,
            ],
            [
                'id'            => 22,
                'name'          => 'entity-dept3-create',
                'display_name'  => 'Department #3 Create',
                'description'   => 'Create new Department #3',
                'type'          => 1,
                'submod_id'     => 8,
            ],
            [
                'id'            => 23,
                'name'          => 'entity-dept3-read',
                'display_name'  => 'Department #3 Read',
                'description'   => 'Read Department #3 data',
                'type'          => 2,
                'submod_id'     => 8,
            ],
            [
                'id'            => 24,
                'name'          => 'entity-dept3-not-allowed',
                'display_name'  => 'Department #3 Not Allowed',
                'description'   => 'Can not allow access Department #3',
                'type'          => 3,
                'submod_id'     => 8,
            ],
            [
                'id'            => 25,
                'name'          => 'entity-dept4-create',
                'display_name'  => 'Department #4 Create',
                'description'   => 'Create new Department #4',
                'type'          => 1,
                'submod_id'     => 9,
            ],
            [
                'id'            => 26,
                'name'          => 'entity-dept4-read',
                'display_name'  => 'Department #4 Read',
                'description'   => 'Read Department #4 data',
                'type'          => 2,
                'submod_id'     => 9,
            ],
            [
                'id'            => 27,
                'name'          => 'entity-dept4-not-allowed',
                'display_name'  => 'Department #4 Not Allowed',
                'description'   => 'Can not allow access Department #4',
                'type'          => 3,
                'submod_id'     => 9,
            ],
            [
                'id'            => 28,
                'name'          => 'entity-grade-create',
                'display_name'  => 'Grade Create',
                'description'   => 'Create new Grade',
                'type'          => 1,
                'submod_id'     => 10,
            ],
            [
                'id'            => 29,
                'name'          => 'entity-grade-read',
                'display_name'  => 'Grade Read',
                'description'   => 'Read Grade data',
                'type'          => 2,
                'submod_id'     => 10,
            ],
            [
                'id'            => 30,
                'name'          => 'entity-grade-not-allowed',
                'display_name'  => 'Grade Not Allowed',
                'description'   => 'Can not allow access Grade',
                'type'          => 3,
                'submod_id'     => 10,
            ],
            [
                'id'            => 31,
                'name'          => 'entity-jobtitle-create',
                'display_name'  => 'Job Title Create',
                'description'   => 'Create new Job Title',
                'type'          => 1,
                'submod_id'     => 11,
            ],
            [
                'id'            => 32,
                'name'          => 'entity-jobtitle-read',
                'display_name'  => 'Job Title Read',
                'description'   => 'Read Job Title data',
                'type'          => 2,
                'submod_id'     => 11,
            ],
            [
                'id'            => 33,
                'name'          => 'entity-jobtitle-not-allowed',
                'display_name'  => 'Job Title Not Allowed',
                'description'   => 'Can not allow access Job Title',
                'type'          => 3,
                'submod_id'     => 11,
            ],
            [
                'id'            => 34,
                'name'          => 'entity-location-create',
                'display_name'  => 'Location Create',
                'description'   => 'Create new Location',
                'type'          => 1,
                'submod_id'     => 12,
            ],
            [
                'id'            => 35,
                'name'          => 'entity-location-read',
                'display_name'  => 'Location Read',
                'description'   => 'Read Location data',
                'type'          => 2,
                'submod_id'     => 12,
            ],
            [
                'id'            => 36,
                'name'          => 'entity-location-not-allowed',
                'display_name'  => 'Location Not Allowed',
                'description'   => 'Can not allow access Location',
                'type'          => 3,
                'submod_id'     => 12,
            ],
            [
                'id'            => 37,
                'name'          => 'entity-maxos-create',
                'display_name'  => 'Maximum OS Create',
                'description'   => 'Create new Maximum OS',
                'type'          => 1,
                'submod_id'     => 13,
            ],
            [
                'id'            => 38,
                'name'          => 'entity-maxos-read',
                'display_name'  => 'Maximum OS Read',
                'description'   => 'Read Maximum OS data',
                'type'          => 2,
                'submod_id'     => 13,
            ],
            [
                'id'            => 39,
                'name'          => 'entity-maxos-not-allowed',
                'display_name'  => 'Maximum OS Not Allowed',
                'description'   => 'Can not allow access Maximum OS',
                'type'          => 3,
                'submod_id'     => 13,
            ],
            [
                'id'            => 40,
                'name'          => 'entity-nontax-create',
                'display_name'  => 'Non-taxable Income Create',
                'description'   => 'Create new Non-taxable Income',
                'type'          => 1,
                'submod_id'     => 14,
            ],
            [
                'id'            => 41,
                'name'          => 'entity-nontax-read',
                'display_name'  => 'Non-taxable Income Read',
                'description'   => 'Read Non-taxable Income data',
                'type'          => 2,
                'submod_id'     => 14,
            ],
            [
                'id'            => 42,
                'name'          => 'entity-nontax-not-allowed',
                'display_name'  => 'Non-taxable Income Not Allowed',
                'description'   => 'Can not allow access Non-taxable Income',
                'type'          => 3,
                'submod_id'     => 14,
            ],
            [
                'id'            => 43,
                'name'          => 'entity-severance-create',
                'display_name'  => 'Severance Tariff Create',
                'description'   => 'Create new Severance Tariff',
                'type'          => 1,
                'submod_id'     => 15,
            ],
            [
                'id'            => 44,
                'name'          => 'entity-severance-read',
                'display_name'  => 'Severance Tariff Read',
                'description'   => 'Read Severance Tariff data',
                'type'          => 2,
                'submod_id'     => 15,
            ],
            [
                'id'            => 45,
                'name'          => 'entity-severance-not-allowed',
                'display_name'  => 'Severance Tariff Not Allowed',
                'description'   => 'Can not allow access Severance Tariff',
                'type'          => 3,
                'submod_id'     => 15,
            ],
            [
                'id'            => 46,
                'name'          => 'entity-tbg-create',
                'display_name'  => 'Tax by Government Create',
                'description'   => 'Create new Tax by Government',
                'type'          => 1,
                'submod_id'     => 16,
            ],
            [
                'id'            => 47,
                'name'          => 'entity-tbg-read',
                'display_name'  => 'Tax by Government Read',
                'description'   => 'Read Tax by Government data',
                'type'          => 2,
                'submod_id'     => 16,
            ],
            [
                'id'            => 48,
                'name'          => 'entity-tbg-not-allowed',
                'display_name'  => 'Tax by Government Not Allowed',
                'description'   => 'Can not allow access Tax by Government',
                'type'          => 3,
                'submod_id'     => 16,
            ],
            [
                'id'            => 49,
                'name'          => 'entity-taxtariff-create',
                'display_name'  => 'Tax Tariff Create',
                'description'   => 'Create new Tax Tariff',
                'type'          => 1,
                'submod_id'     => 17,
            ],
            [
                'id'            => 50,
                'name'          => 'entity-taxtariff-read',
                'display_name'  => 'Tax Tariff Read',
                'description'   => 'Read Tax Tariff data',
                'type'          => 2,
                'submod_id'     => 17,
            ],
            [
                'id'            => 51,
                'name'          => 'entity-taxtariff-not-allowed',
                'display_name'  => 'Tax Tariff Not Allowed',
                'description'   => 'Can not allow access Tax Tariff',
                'type'          => 3,
                'submod_id'     => 17,
            ],
            [
                'id'            => 52,
                'name'          => 'entity-team-create',
                'display_name'  => 'Team Create',
                'description'   => 'Create new Team',
                'type'          => 1,
                'submod_id'     => 18,
            ],
            [
                'id'            => 53,
                'name'          => 'entity-team-read',
                'display_name'  => 'Team Read',
                'description'   => 'Read Team data',
                'type'          => 2,
                'submod_id'     => 18,
            ],
            [
                'id'            => 54,
                'name'          => 'entity-team-not-allowed',
                'display_name'  => 'Team Not Allowed',
                'description'   => 'Can not allow access Team',
                'type'          => 3,
                'submod_id'     => 18,
            ],
            [
                'id'            => 55,
                'name'          => 'ps-pa-create',
                'display_name'  => 'Payroll Account Create',
                'description'   => 'Create new Payroll Account',
                'type'          => 1,
                'submod_id'     => 19,
            ],
            [
                'id'            => 56,
                'name'          => 'ps-pa-read',
                'display_name'  => 'Payroll Account Read',
                'description'   => 'Read Payroll Account data',
                'type'          => 2,
                'submod_id'     => 19,
            ],
            [
                'id'            => 57,
                'name'          => 'ps-pa-not-allowed',
                'display_name'  => 'Payroll Account Not Allowed',
                'description'   => 'Can not allow access Payroll Account',
                'type'          => 3,
                'submod_id'     => 19,
            ],
            [
                'id'            => 58,
                'name'          => 'personnel-emp-create',
                'display_name'  => 'Employee Create',
                'description'   => 'Create new Employee',
                'type'          => 1,
                'submod_id'     => 20,
            ],
            [
                'id'            => 59,
                'name'          => 'personnel-emp-read',
                'display_name'  => 'Employee Read',
                'description'   => 'Read Employee data',
                'type'          => 2,
                'submod_id'     => 20,
            ],
            [
                'id'            => 60,
                'name'          => 'personnel-emp-not-allowed',
                'display_name'  => 'Employee Not Allowed',
                'description'   => 'Can not allow access Employee',
                'type'          => 3,
                'submod_id'     => 20,
            ],
            [
                'id'            => 61,
                'name'          => 'personnel-import-create',
                'display_name'  => 'Import Employee Create',
                'description'   => 'Able to Import Employee',
                'type'          => 1,
                'submod_id'     => 21,
            ],
            [
                'id'            => 62,
                'name'          => 'personnel-import-not-allowed',
                'display_name'  => 'Import Employee Not Allowed',
                'description'   => 'Can not allow access Import Employee',
                'type'          => 3,
                'submod_id'     => 21,
            ],
            [
                'id'            => 63,
                'name'          => 'payroll-ve-create',
                'display_name'  => 'Variable Income Create',
                'description'   => 'Create new Variable Income',
                'type'          => 1,
                'submod_id'     => 22,
            ],
            [
                'id'            => 64,
                'name'          => 'payroll-ve-read',
                'display_name'  => 'Variable Income Read',
                'description'   => 'Read Variable Income data',
                'type'          => 2,
                'submod_id'     => 22,
            ],
            [
                'id'            => 65,
                'name'          => 'payroll-ve-not-allowed',
                'display_name'  => 'Variable Income Not Allowed',
                'description'   => 'Can not allow access Variable Income',
                'type'          => 3,
                'submod_id'     => 22,
            ],
            [
                'id'            => 66,
                'name'          => 'payroll-import-create',
                'display_name'  => 'Import Income Create',
                'description'   => 'Able to Import Income',
                'type'          => 1,
                'submod_id'     => 23,
            ],
            [
                'id'            => 67,
                'name'          => 'payroll-import-not-allowed',
                'display_name'  => 'Import Income Not Allowed',
                'description'   => 'Can not allow access Import Income',
                'type'          => 3,
                'submod_id'     => 23,
            ],
            [
                'id'            => 68,
                'name'          => 'payroll-process-create',
                'display_name'  => 'Payroll Process Create',
                'description'   => 'Able to Payroll Process',
                'type'          => 1,
                'submod_id'     => 24,
            ],
            [
                'id'            => 69,
                'name'          => 'payroll-process-not-allowed',
                'display_name'  => 'Payroll Process Not Allowed',
                'description'   => 'Can not allow access Payroll Process',
                'type'          => 3,
                'submod_id'     => 24,
            ],
            [
                'id'            => 70,
                'name'          => 'payroll-closing-create',
                'display_name'  => 'Payroll Closing Create',
                'description'   => 'Able to Payroll Closing',
                'type'          => 1,
                'submod_id'     => 25,
            ],
            [
                'id'            => 71,
                'name'          => 'payroll-closing-not-allowed',
                'display_name'  => 'Payroll Closing Not Allowed',
                'description'   => 'Can not allow access Payroll Closing',
                'type'          => 3,
                'submod_id'     => 25,
            ],
            [
                'id'            => 72,
                'name'          => 'payroll-setback-create',
                'display_name'  => 'Payroll Set Back Create',
                'description'   => 'Able to Payroll Set Back',
                'type'          => 1,
                'submod_id'     => 26,
            ],
            [
                'id'            => 73,
                'name'          => 'payroll-setback-not-allowed',
                'display_name'  => 'Payroll Set Back Not Allowed',
                'description'   => 'Can not allow access Payroll Set Back',
                'type'          => 3,
                'submod_id'     => 26,
            ],
            [
                'id'            => 74,
                'name'          => 'report-detail-create',
                'display_name'  => 'Generate Report Payroll Detail',
                'description'   => 'Able to generate payroll detail report',
                'type'          => 1,
                'submod_id'     => 27,
            ],
            [
                'id'            => 75,
                'name'          => 'report-detail-not-allowed',
                'display_name'  => 'Payroll Detail Report Not Allowed',
                'description'   => 'Can not allow access payroll detail report',
                'type'          => 3,
                'submod_id'     => 27,
            ],
            [
                'id'            => 76,
                'name'          => 'report-bpjsw-create',
                'display_name'  => 'Generate Report BPJS Ketenagakerjaan',
                'description'   => 'Able to generate report BPJS Ketenagakerjaan',
                'type'          => 1,
                'submod_id'     => 28,
            ],
            [
                'id'            => 77,
                'name'          => 'report-bpjsw-not-allowed',
                'display_name'  => 'BPJS Ketenagakerjaan Report Not Allowed',
                'description'   => 'Can not allow access report BPJS Ketenagakerjaan',
                'type'          => 3,
                'submod_id'     => 28,
            ],
            [
                'id'            => 78,
                'name'          => 'report-bpjsh-create',
                'display_name'  => 'Generate Report BPJS Kesehatan',
                'description'   => 'Able to generate report BPJS Kesehatan',
                'type'          => 1,
                'submod_id'     => 29,
            ],
            [
                'id'            => 79,
                'name'          => 'report-bpjsh-not-allowed',
                'display_name'  => 'BPJS Kesehatan Report Not Allowed',
                'description'   => 'Can not allow access report BPJS Kesehatan',
                'type'          => 3,
                'submod_id'     => 29,
            ],
            [
                'id'            => 80,
                'name'          => 'report-payslip-create',
                'display_name'  => 'Generate Report Payslip',
                'description'   => 'Able to generate Payslip',
                'type'          => 1,
                'submod_id'     => 30,
            ],
            [
                'id'            => 81,
                'name'          => 'report-payslip-not-allowed',
                'display_name'  => 'Payslip Not Allowed',
                'description'   => 'Can not allow access Payslip',
                'type'          => 3,
                'submod_id'     => 30,
            ],
            [
                'id'            => 82,
                'name'          => 'report-espt-create',
                'display_name'  => 'Generate e-SPT',
                'description'   => 'Able to generate report e-SPT',
                'type'          => 1,
                'submod_id'     => 31,
            ],
            [
                'id'            => 83,
                'name'          => 'report-espt-not-allowed',
                'display_name'  => 'E-SPT Not Allowed',
                'description'   => 'Can not allow access e-SPT',
                'type'          => 3,
                'submod_id'     => 31,
            ],
            [
                'id'            => 84,
                'name'          => 'report-bank-create',
                'display_name'  => 'Generate Transfer & Cash Report',
                'description'   => 'Able to generate report transfer & cash',
                'type'          => 1,
                'submod_id'     => 32,
            ],
            [
                'id'            => 85,
                'name'          => 'report-bank-not-allowed',
                'display_name'  => 'Transfer & Cash Report Not Allowed',
                'description'   => 'Can not allow access transfer & cash',
                'type'          => 3,
                'submod_id'     => 32,
            ],
            [
                'id'            => 86,
                'name'          => 'report-taxform-create',
                'display_name'  => 'Generate Report Tax Form',
                'description'   => 'Able to generate tax form',
                'type'          => 1,
                'submod_id'     => 33,
            ],
            [
                'id'            => 87,
                'name'          => 'report-taxform-not-allowed',
                'display_name'  => 'Tax Form Not Allowed',
                'description'   => 'Can not allow access tax form',
                'type'          => 3,
                'submod_id'     => 33,
            ],
            [
                'id'            => 88,
                'name'          => 'report-custom-create',
                'display_name'  => 'Generate Custom Report',
                'description'   => 'Able to generate custom report',
                'type'          => 1,
                'submod_id'     => 34,
            ],
            [
                'id'            => 89,
                'name'          => 'report-custom-not-allowed',
                'display_name'  => 'Custom Report Not Allowed',
                'description'   => 'Can not allow access custom report',
                'type'          => 3,
                'submod_id'     => 34,
            ],
            [
                'id'            => 90,
                'name'          => 'usermgm-user-create',
                'display_name'  => 'User Create',
                'description'   => 'Create new user',
                'type'          => 1,
                'submod_id'     => 35,
            ],
            [
                'id'            => 91,
                'name'          => 'usermgm-user-read',
                'display_name'  => 'User Read',
                'description'   => 'Read user data',
                'type'          => 2,
                'submod_id'     => 35,
            ],
            [
                'id'            => 92,
                'name'          => 'usermgm-user-not-allowed',
                'display_name'  => 'User Not Allowed',
                'description'   => 'Can not allow access user',
                'type'          => 3,
                'submod_id'     => 35,
            ],
            [
                'id'            => 93,
                'name'          => 'usermgm-group-create',
                'display_name'  => 'Group Create',
                'description'   => 'Create new group',
                'type'          => 1,
                'submod_id'     => 36,
            ],
            [
                'id'            => 94,
                'name'          => 'usermgm-group-read',
                'display_name'  => 'Group Read',
                'description'   => 'Read group data',
                'type'          => 2,
                'submod_id'     => 36,
            ],
            [
                'id'            => 95,
                'name'          => 'usermgm-group-not-allowed',
                'display_name'  => 'Group Not Allowed',
                'description'   => 'Can not allow access user',
                'type'          => 3,
                'submod_id'     => 36,
            ],
        ]);
    }
}
